---
title: "data-hygiene-practices"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goals

1. Reduce time spent on data cleaning/munging.
2. Produce 'tidy' data sets that can be easily updated, shared, re-used.

# Best practices

## Data file formats

- Store and save data files as text, preferably in comma-separated value (CSV) format.

```
variable_1,"variable 2",variable_3,variable_4
1, "A",TRUE,2017-07-04
2, "Z",FALSE,2017-07-04

```

*Note*: First row contains variable/column names. There are no spaces between variables. Each row of the data file ends with an (invisible) line feed/return character. If your variable name has spaces in it, you must surround the name with quotation marks, e.g., `"variable 2"`.

- Save data files in the rawest, most 'micro' state possible
    - trial-by-trial, response-by-response
    - separate files for each participant & measure & session
- Write scripts/syntax to aggregate files across participants & measures

- Adopt a 'tidy' data ([Wickham, 2014](http://dx.doi.org/10.18637/jss.v059.i10)) format
    - Each row is an observation
    - Each column is a variable
    - Files are 'rectangular'
    - Files are usually 'longer' than they are wide
    - Each cell is filled, even with `NA` if needed.

## Naming conventions

- Avoid spaces in file names (& variable names); instead, use hyphens "-" or underscores "_" to separate multiple words or elements to make file names human readable.
    - This makes file names "parsable"
    - If important metadata (e.g., participant ID, condition, or test date) aren't in the file, put them in the file name: `<participant-id>-<YYYY-MM-DD>-condA.csv`
        - `p001-2017-07-31-condA.csv`
        - `p001-2017-07-30-condB.csv`
- Similarly, avoid special characters in file names, see ([Broman & Lee, 2017](https://github.com/kbroman/Paper_DataOrg/blob/master/manuscript.md#choose-good-names-for-things)).
- When using dates, use the YYYY-MM-DD format.
- Zero-pad numbers (~~2~~ -> 002), so that your file names of a similar type have the same length.
    
## Data directories

- Choose an organizational scheme and stick with it for the duration of your project.
    - By participant, by measure
        - `p001/survey/p001-2017-07-31-survey.csv`
        - `p001/stroop/p001-2017-07-31-stroop.csv`
    - By measure, by participant
        - `survey/p001/...`
        - `stroop/p001/...`
- If you have non-text source files, e.g., `*.xlsx`, duplicate the above structure for each data file format type.
    - `data/csv/p001/...`
    - `data/xlsx/p001/...`
    - `data/xlsx/survey/...`
    - `data/csv/stroop/...`
    
## Create data dictionaries

- See ([Broman & Lee, 2017](https://github.com/kbroman/Paper_DataOrg/blob/master/manuscript.md#create-a-data-dictionary))

## Making data 'tidy'




